### ISSUE TITLE
[FEATURE_REQUEST] - Add option to change the sender in email template

### ISSUE THREAD

**Issue by JensVanhulst** [Tontonjo/proxmox#2]
I ran your script today and successfully configured my emailing in proxmox. But when I received the email,
the name of the sender is : `HOSTNAME-alert`.

According to a blog post on the proxmox forum it is possible to change that.
SOURCE : https://forum.proxmox.com/threads/get-postfix-to-send-notifications-email-externally.59940/

---------------------------------------------------------
**Create smtp_header_checks file, this changes all outgoing mail**:
/^From:.*/ REPLACE From: HOSTNAME-alert <HOSTNAME-alert@something.com>

Add to main.cf:
smtp_header_checks = pcre:/etc/postfix/smtp_header_checks

---------------------------------------------------------

Maybe it is a nice feature to add to your script

**Comment by Tontonjo** [comment]
Hello!
Thanks for your suggestion, will think about it if i have some times.

Can you explain to me what are the use case that would need you to edit this?
In you example you use an email adress wich already should appears as it's used to send the notification.

What are the use case for this?

**Comment by JensVanhulst** [comment]
Hi @Tontonjo  sorry it took so long to respond. The reason I want to edit the email is because I have multiple proxmox servers and I ran this script on all of them. 

When an alert comes in as "HOSTNAME-alert". I cannot indentify on which server the alert triggered (based on the hostname). I also cannot group the mails into different folders eg. SERVER001, SERVER002. .... since it is all coming from the same sender. 

I hope this is clear for you. Much appreciated if you could implement this !

**Comment by Tontonjo** [comment]
Sorry for the delay - now i understand,

I'm not sure how i could implement this as this is not something you usually need and i feel asking for "not usually necessary" questions do complicate the script.

Do you have any suggestion to get a compromise where people are not asked for this change?

PS: ez mail configurator is now part of Proxmox Toolbox at https://github.com/Tontonjo/proxmox_toolbox
